### ISSUE TITLE
Find out why phantomjs gem is in the main deps and what it is needed for

### ISSUE THREAD

**Issue by casaper** [panter/mykonote#302]
Phantomjs is discontinued since quite a while. If ever possible this dependency should be removed.

**Comment by koffeinfrei** [comment]
The script https://github.com/panter/mykonote/blob/master/app/services/note_content_cleaner.rb which is used to cleanup html content be be quill compatible (task: https://github.com/panter/mykonote/blob/master/lib/tasks/data.rake) still depends on it. I tried to replace it with another headless option (I think) but phantom is still the best option currently.

**Comment by casaper** [comment]
> phantom is still the best option currently.

How about a purely client side solution for this? Would that be a potential solution?

Anyways. Just picked this up on the move, and I am totally not in the topic nor in Mykonote.

Happy new Year @koffeinfrei

**Comment by koffeinfrei** [comment]
> How about a purely client side solution for this? Would that be a potential solution?

The script is supposed to run on the server, after importing notes (e.g. from evernote).

> Anyways. Just picked this up on the move, and I am totally not in the topic nor in Mykonote.

Sure thing. Just wanted to let you know why this relic is still in use.

> Happy new Year @koffeinfrei

Happy New Year to you too.
