### ISSUE TITLE
Port the web client to run with webpacker instead of seperate react app

### ISSUE THREAD

**Issue by casaper** [panter/mykonote#306]
That will probably make a heroku deployment much smoother, because that will then be a standard rails setup

**Comment by koffeinfrei** [comment]
This project actually started out that way. Webpacker was painful when I tried it last time, which was quite some year ago though.

Anyway, the real reason to use create-react-app is that a clear separation by client and server/api is needed to make use of the pseudo-offline functionality, and the autosave cycle.
